### ISSUE TITLE
Get rid of `replace media sources`

### ISSUE THREAD

**Issue by ewen-lbh** [ortfo/db#28]
It shouldn't be needed to remove paths to the portfolio dir. like this:

```yaml
replace media sources:
  - replace: /mnt/datacore/projects/
    with: ''
  - replace: /home/ewen/projects/
    with: ''
```
