### ISSUE TITLE
Configuration: new config `default id template`

### ISSUE THREAD

**Issue by ewen-lbh** [ortfo/db#33]
Allows to specify a template to auto-fill IDs for the different types of elements of a description. In each, `<number>` (and `<n>` for short?) is replaced with the element's index's successor (i.e. an index that starts at one) and `<index>` is replaced with the 0-based index. `<slug>` is also available: the slug of:

- the first line for a paragraph;
- the alt text (or the href if alt text is empty) for a link; and
- the media source for a media.

example:

```yaml
default id template:
  paragraph: p<number>
  media: m<number>
  link: l<number>
```
